#!/usr/bin/env python3
"""Render README.md and entries/<slug>.md from data/entries/*.yaml.

README = docs/readme_intro.md (hand-written source) + generated tables.
Everything this script writes carries a GENERATED marker; never hand-edit it.
Sort: by system, then by name (case-insensitive). No ordering by stars, ever.
"""
import pathlib

import yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent
ENTRIES_DIR = ROOT / "data" / "entries"
OUT_PAGES = ROOT / "entries"

SYSTEM_ORDER = ["Coq/Rocq", "Lean 4", "Isabelle/HOL", "Why3", "Dafny", "F*"]

MARKER = ("<!-- GENERATED by scripts/render.py from data/entries/ — "
          "do not hand-edit below this line -->")

def fmt(v):
    if v is None or v == "":
        return "unknown"
    if isinstance(v, list):
        return ", ".join(str(x) for x in v)
    return str(v)

def load():
    entries = []
    for p in sorted(ENTRIES_DIR.glob("*.yaml")):
        e = yaml.safe_load(p.read_text())
        e["_slug"] = p.stem
        entries.append(e)
    return entries

def system_key(e):
    s = e.get("system") or "zz-unknown"
    try:
        return (0, SYSTEM_ORDER.index(s), "")
    except ValueError:
        return (1, 0, s.lower())

def table(rows):
    head = ("| Name | System | Role | Verifies | Status | Description |\n"
            "|---|---|---|---|---|---|")
    lines = [head]
    for e in rows:
        name = f"[{fmt(e.get('name'))}](entries/{e['_slug']}.md)"
        lines.append("| " + " | ".join([
            name, fmt(e.get("system")), fmt(e.get("role")),
            fmt(e.get("verifies")), fmt(e.get("status")),
            fmt(e.get("description")).replace("|", "\\|"),
        ]) + " |")
    return "\n".join(lines)

def render_page(e):
    fields = ["repo_url", "system", "role", "verifies", "paper", "authors",
              "licence", "stars", "last_commit", "status", "builds",
              "build_date", "toolchain", "source", "notes"]
    lines = [MARKER, "", f"# {fmt(e.get('name'))}", "",
             fmt(e.get("description")), ""]
    for f in fields:
        if f in ("build_date", "toolchain") and e.get("builds") in (None, "not-attempted"):
            continue
        label = f.replace("_", " ")
        val = fmt(e.get(f))
        if f == "repo_url" and val != "unknown":
            val = f"<{val}>"
        lines.append(f"- **{label}**: {val}")
    lines += ["", "[Back to catalog](../README.md)", ""]
    return "\n".join(lines)

def main():
    entries = load()
    intro = (ROOT / "docs" / "readme_intro.md").read_text()

    interactive = [e for e in entries if not e.get("automated")]
    automated = [e for e in entries if e.get("automated")]

    parts = [intro.rstrip(), "", MARKER, ""]
    parts.append(f"*{len(entries)} entries. Generated from "
                 f"[`data/entries/`](data/entries/) by "
                 f"[`scripts/render.py`](scripts/render.py); "
                 f"stars/dates refreshed weekly by CI.*\n")

    def section(title, rows):
        if not rows:
            return
        parts.append(f"## {title}\n")
        rows = sorted(rows, key=lambda e: (system_key(e), fmt(e.get("name")).lower()))
        cur = object()
        group = []
        for e in rows + [None]:
            s = e.get("system") if e else None
            if s != cur:
                if group:
                    parts.append(f"### {fmt(cur)}\n")
                    parts.append(table(group) + "\n")
                cur, group = s, []
            if e:
                group.append(e)

    section("Proof-assistant developments", interactive)
    section("Automated and SMT-backed tools", automated)

    (ROOT / "README.md").write_text("\n".join(parts))

    OUT_PAGES.mkdir(exist_ok=True)
    for old in OUT_PAGES.glob("*.md"):
        old.unlink()
    for e in entries:
        (OUT_PAGES / f"{e['_slug']}.md").write_text(render_page(e))
    print(f"rendered README.md + {len(entries)} entry pages")

if __name__ == "__main__":
    main()
